# Generated by Django 2.2.4 on 2020-11-12 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantedwish',
            name='the_time_wish_was_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 30, 49, 734415)),
        ),
    ]
