# Generated by Django 2.2.4 on 2020-11-14 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201114_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingwish',
            name='number_of_likes',
        ),
        migrations.AlterField(
            model_name='grantedwish',
            name='the_time_wish_was_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 12, 54, 52, 983683)),
        ),
    ]
