# Generated by Django 2.2.4 on 2020-11-14 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201114_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedwish',
            name='the_time_wish_was_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 13, 0, 15, 238356)),
        ),
    ]
